run_config_name: nerc_config # for saving info files/logs

event: '2021-05-12' # make all option
# No start/stop time needed for NERC, preset in config.py

data_source: ['NERC'] # If specified, only return sites with this data source (e.g., TVA, NERC, SWMF)

data_type: ['GIC','B'] # If specified, only return sites with this data type (e.g., GIC, B)

data_class: ['measured'] # If specified, only return sites with this data class (e.g., measured, calculated)

exclude_errors: null # If specified, excludes sites with known data issues ('all', 'manual', 'automated', or null)

summary_table: False # If True, creates a summary table of site statistics and metrics

filter_kwargs: # for filter.py, maybe set per event? (filter.yaml with defaults)
  spike_filt_type: 'median' # 'difference' or 'median' or null
  low_signal_threshold: 4 # [A]
  baseline_buffer: 1 # [A]
  spike_threshold: 40 # [A]
  median_window: 20 # [number of points]
  noise_threshold: 4 # [unitless]
  max_cadence: 60 # [s]
  max_gap: 600 # [s]
  max_const: 300 # [s]
# check for other undocumented kwargs lying abt filter.py