run_config_name: test_config # for saving info files/logs

event: '2024-05-10'
start_time: 2024-05-10 #unclear if these are needed, already included in config.py
stop_time: 2024-05-13

data_source: 'NERC' # If specified, only return sites with this data source (e.g., TVA, NERC, SWMF)

data_type: 'GIC' # If specified, only return sites with this data type (e.g., GIC, B)

data_class: 'measured' # If specified, only return sites with this data class (e.g., measured, calculated)

exclude_errors: True # If True, excludes sites with known data issues (see info.csv 'manual_error' column)

filter_kwargs: # for filter.py
  spike_filt_type: 'difference' # 'difference' or 'median' or None
  low_signal_threshold: 4 # [A]
  baseline_buffer: 1 # [A]
  spike_threshold: 40 # [A]
  median_window: 20 # [number of points]
  noise_threshold: 4 # [unitless]
  max_cadence: 60 # [s]
  max_gap: 600 # [s]
  max_const: 300 # [s]
# check for other undocumented kwargs lying abt filter.py